[project]
name = "mazegen"
version = "1.0.0"
description = "Maze Generator"
authors = [
    {name = "lucpelle, lobroue"}
]
# Subject R1: minimum Python 3.10 (more portable than 3.13)
requires-python = ">=3.10"
dependencies = [
    "pydantic"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"